name: build and push

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_ACCESS_TOKEN }}

      - name: Build
        run: make build

      - name: Push
        if: github.ref == 'refs/heads/master'
        run: make push
